import "package:flutter/foundation.dart";
import "package:flutter/material.dart";
import "package:flutter/services.dart";
import "package:pjsk_sticker/image_text_overlay.dart";

class TextLayer {
  final String id;
  String content;
  Offset pos;
  double lean;
  double fontSize;
  int edgeSize;
  int font;
  bool useCustomColor;
  Color customColor;

  TextLayer({
    String? id,
    required this.content,
    this.pos = const Offset(20, 10),
    this.lean = 15,
    this.fontSize = 50,
    this.edgeSize = 4,
    this.font = 1,
    this.useCustomColor = false,
    this.customColor = const Color(0xFFDDAACC),
  }) : id = id ?? DateTime.now().microsecondsSinceEpoch.toString();

  Map<String, dynamic> toJson() => {
    'i': id,
    'c': content,
    'x': pos.dx,
    'y': pos.dy,
    'r': lean,
    's': fontSize,
    'e': edgeSize,
    'f': font,
    'u': useCustomColor,
    'clr': customColor.toARGB32(),
  };

  factory TextLayer.fromJson(Map<String, dynamic> json) => TextLayer(
    id: json['i'] ?? json['id'],
    content: json['c'] ?? json['content'] ?? "",
    pos: Offset(
      (json['x'] ?? json['pos_x'] ?? 20).toDouble(),
      (json['y'] ?? json['pos_y'] ?? 10).toDouble(),
    ),
    lean: (json['r'] ?? json['lean'] ?? 15).toDouble(),
    fontSize: (json['s'] ?? json['fontSize'] ?? 50).toDouble(),
    edgeSize: json['e'] ?? json['edgeSize'] ?? 4,
    font: json['f'] ?? json['font'] ?? 1,
    useCustomColor: json['u'] ?? json['useCustomColor'] ?? false,
    customColor: Color(json['clr'] ?? json['customColor'] ?? 0xFFDDAACC),
  );

  TextLayer copyWith({
    String? content,
    Offset? pos,
    double? lean,
    double? fontSize,
    int? edgeSize,
    int? font,
    bool? useCustomColor,
    Color? customColor,
  }) => TextLayer(
    id: id,
    content: content ?? this.content,
    pos: pos ?? this.pos,
    lean: lean ?? this.lean,
    fontSize: fontSize ?? this.fontSize,
    edgeSize: edgeSize ?? this.edgeSize,
    font: font ?? this.font,
    useCustomColor: useCustomColor ?? this.useCustomColor,
    customColor: customColor ?? this.customColor,
  );
}

class PjskGenerator {
  static final Map<String, Uint8List> _imageCache = {};
  static final Map<int, Uint8List> _fontCache = {};

  static final List<String> groups = [
    "バーチャル・シンガー",
    "Leo/need",
    "MORE MORE JUMP!",
    "Vivid BAD SQUAD",
    "ワンダーランズ×ショウタイム",
    "25時、ナイトコードで。",
  ];

  static final Map<String, Color> groupColor = {
    "バーチャル・シンガー": Color.fromARGB(255, 0, 176, 240), // #00B0F0 虚拟歌手
    "Leo/need": Color.fromARGB(255, 0, 112, 192), // #0070C0 深蓝
    "MORE MORE JUMP!": Color.fromARGB(255, 255, 153, 204), // #FF99CC 粉红
    "Vivid BAD SQUAD": Color.fromARGB(255, 179, 153, 212), // #B399D4 紫色
    "ワンダーランズ×ショウタイム": Color.fromARGB(255, 255, 102, 0), // #FF6600 橙色
    "25時、ナイトコードで。": Color.fromARGB(255, 112, 48, 160), // #7030A0 深紫
  };

  static final Map<String, List<String>> groupMembers = {
    "バーチャル・シンガー": ["初音ミク", "鏡音リン", "鏡音レン", "巡音ルカ", "MEIKO", "KAITO"],
    "Leo/need": ["星乃一歌", "天馬咲希", "望月穂波", "日野森志歩"],
    "MORE MORE JUMP!": ["花里みのり", "桐谷遥", "桃井愛莉", "日野森雫"],
    "Vivid BAD SQUAD": ["小豆こはね", "白石杏", "東雲彰人", "青柳冬弥"],
    "ワンダーランズ×ショウタイム": ["天馬司", "鳳えむ", "草薙寧々", "神代類"],
    "25時、ナイトコードで。": ["宵崎奏", "朝比奈まふゆ", "東雲絵名", "暁山瑞希"],
  };

  static final Map<String, String> characterMap = {
    // バーチャル・シンガー
    "初音ミク": "miku",
    "鏡音リン": "rin",
    "鏡音レン": "len",
    "巡音ルカ": "luka",
    "MEIKO": "meiko",
    "KAITO": "kaito",
    // Leo/need
    "星乃一歌": "ichika",
    "天馬咲希": "saki",
    "望月穂波": "honami",
    "日野森志歩": "shiho",
    // MORE MORE JUMP!
    "花里みのり": "minori",
    "桐谷遥": "haruka",
    "桃井愛莉": "airi",
    "日野森雫": "shizuku",
    // Vivid BAD SQUAD
    "小豆こはね": "kohane",
    "白石杏": "an",
    "東雲彰人": "akito",
    "青柳冬弥": "touya",
    // ワンダーランズ×ショウタイム
    "天馬司": "tsukasa",
    "鳳えむ": "emu",
    "草薙寧々": "nene",
    "神代類": "rui",
    // 25時、ナイトコードで。
    "宵崎奏": "kanade",
    "朝比奈まふゆ": "mafuyu",
    "東雲絵名": "ena",
    "暁山瑞希": "mizuki",
  };

  static final Map<String, List<String>> characterStickers = {
    'airi': [
      'airi1.png',
      'airi10.png',
      'airi11.png',
      'airi12.png',
      'airi13.png',
      'airi14.png',
      'airi15.png',
      'airi16.png',
      'airi17.png',
      'airi18.png',
      'airi19.png',
      'airi2.png',
      'airi20.png',
      'airi21.png',
      'airi22.png',
      'airi23.png',
      'airi24.png',
      'airi25.png',
      'airi26.png',
      'airi27.png',
      'airi28.png',
      'airi29.png',
      'airi3.png',
      'airi30.png',
      'airi4.png',
      'airi5.png',
      'airi6.png',
      'airi7.png',
      'airi8.png',
      'airi9.png',
    ],
    'akito': [
      'akito1.png',
      'akito10.png',
      'akito11.png',
      'akito12.png',
      'akito13.png',
      'akito14.png',
      'akito15.png',
      'akito16.png',
      'akito17.png',
      'akito18.png',
      'akito19.png',
      'akito2.png',
      'akito20.png',
      'akito21.png',
      'akito22.png',
      'akito23.png',
      'akito24.png',
      'akito25.png',
      'akito26.png',
      'akito27.png',
      'akito28.png',
      'akito3.png',
      'akito4.png',
      'akito5.png',
      'akito6.png',
      'akito7.png',
      'akito8.png',
      'akito9.png',
    ],
    'an': [
      'an1.png',
      'an10.png',
      'an11.png',
      'an12.png',
      'an13.png',
      'an14.png',
      'an15.png',
      'an16.png',
      'an17.png',
      'an18.png',
      'an19.png',
      'an2.png',
      'an20.png',
      'an21.png',
      'an22.png',
      'an23.png',
      'an24.png',
      'an25.png',
      'an26.png',
      'an27.png',
      'an28.png',
      'an29.png',
      'an3.png',
      'an30.png',
      'an4.png',
      'an5.png',
      'an6.png',
      'an7.png',
      'an8.png',
      'an9.png',
    ],
    'emu': [
      'emu1.png',
      'emu10.png',
      'emu11.png',
      'emu12.png',
      'emu13.png',
      'emu14.png',
      'emu15.png',
      'emu16.png',
      'emu17.png',
      'emu18.png',
      'emu19.png',
      'emu2.png',
      'emu20.png',
      'emu21.png',
      'emu22.png',
      'emu23.png',
      'emu24.png',
      'emu25.png',
      'emu26.png',
      'emu27.png',
      'emu3.png',
      'emu4.png',
      'emu5.png',
      'emu6.png',
      'emu7.png',
      'emu8.png',
      'emu9.png',
    ],
    'ena': [
      'ena1.png',
      'ena10.png',
      'ena11.png',
      'ena12.png',
      'ena13.png',
      'ena14.png',
      'ena15.png',
      'ena16.png',
      'ena17.png',
      'ena18.png',
      'ena19.png',
      'ena2.png',
      'ena20.png',
      'ena21.png',
      'ena22.png',
      'ena23.png',
      'ena24.png',
      'ena25.png',
      'ena26.png',
      'ena27.png',
      'ena28.png',
      'ena29.png',
      'ena3.png',
      'ena4.png',
      'ena5.png',
      'ena6.png',
      'ena7.png',
      'ena8.png',
      'ena9.png',
    ],
    'honami': [
      'honami1.png',
      'honami10.png',
      'honami11.png',
      'honami12.png',
      'honami13.png',
      'honami14.png',
      'honami15.png',
      'honami16.png',
      'honami17.png',
      'honami18.png',
      'honami19.png',
      'honami2.png',
      'honami20.png',
      'honami21.png',
      'honami22.png',
      'honami23.png',
      'honami24.png',
      'honami25.png',
      'honami26.png',
      'honami27.png',
      'honami28.png',
      'honami29.png',
      'honami3.png',
      'honami30.png',
      'honami4.png',
      'honami5.png',
      'honami6.png',
      'honami7.png',
      'honami8.png',
      'honami9.png',
    ],
    'ichika': [
      'ichika1.png',
      'ichika10.png',
      'ichika11.png',
      'ichika12.png',
      'ichika13.png',
      'ichika14.png',
      'ichika15.png',
      'ichika16.png',
      'ichika17.png',
      'ichika18.png',
      'ichika19.png',
      'ichika2.png',
      'ichika20.png',
      'ichika21.png',
      'ichika22.png',
      'ichika23.png',
      'ichika24.png',
      'ichika25.png',
      'ichika26.png',
      'ichika27.png',
      'ichika28.png',
      'ichika29.png',
      'ichika3.png',
      'ichika30.png',
      'ichika31.png',
      'ichika32.png',
      'ichika33.png',
      'ichika4.png',
      'ichika5.png',
      'ichika6.png',
      'ichika7.png',
      'ichika8.png',
      'ichika9.png',
    ],
    'kaito': [
      'kaito1.png',
      'kaito10.png',
      'kaito11.png',
      'kaito12.png',
      'kaito13.png',
      'kaito14.png',
      'kaito15.png',
      'kaito16.png',
      'kaito17.png',
      'kaito18.png',
      'kaito19.png',
      'kaito2.png',
      'kaito20.png',
      'kaito21.png',
      'kaito22.png',
      'kaito23.png',
      'kaito24.png',
      'kaito25.png',
      'kaito26.png',
      'kaito27.png',
      'kaito28.png',
      'kaito29.png',
      'kaito3.png',
      'kaito30.png',
      'kaito31.png',
      'kaito4.png',
      'kaito5.png',
      'kaito6.png',
      'kaito7.png',
      'kaito8.png',
      'kaito9.png',
    ],
    'kanade': [
      'kanade1.png',
      'kanade10.png',
      'kanade11.png',
      'kanade12.png',
      'kanade13.png',
      'kanade14.png',
      'kanade15.png',
      'kanade16.png',
      'kanade17.png',
      'kanade18.png',
      'kanade19.png',
      'kanade2.png',
      'kanade20.png',
      'kanade21.png',
      'kanade22.png',
      'kanade23.png',
      'kanade24.png',
      'kanade25.png',
      'kanade26.png',
      'kanade27.png',
      'kanade28.png',
      'kanade29.png',
      'kanade3.png',
      'kanade30.png',
      'kanade31.png',
      'kanade32.png',
      'kanade33.png',
      'kanade4.png',
      'kanade5.png',
      'kanade6.png',
      'kanade7.png',
      'kanade8.png',
      'kanade9.png',
    ],
    'kohane': [
      'kohane1.png',
      'kohane10.png',
      'kohane11.png',
      'kohane12.png',
      'kohane13.png',
      'kohane14.png',
      'kohane15.png',
      'kohane16.png',
      'kohane17.png',
      'kohane18.png',
      'kohane19.png',
      'kohane2.png',
      'kohane20.png',
      'kohane21.png',
      'kohane22.png',
      'kohane23.png',
      'kohane24.png',
      'kohane25.png',
      'kohane26.png',
      'kohane27.png',
      'kohane28.png',
      'kohane29.png',
      'kohane3.png',
      'kohane4.png',
      'kohane5.png',
      'kohane6.png',
      'kohane7.png',
      'kohane8.png',
      'kohane9.png',
    ],
    'len': [
      'len1.png',
      'len10.png',
      'len11.png',
      'len12.png',
      'len13.png',
      'len14.png',
      'len15.png',
      'len16.png',
      'len17.png',
      'len18.png',
      'len19.png',
      'len2.png',
      'len20.png',
      'len21.png',
      'len22.png',
      'len23.png',
      'len24.png',
      'len25.png',
      'len26.png',
      'len27.png',
      'len28.png',
      'len29.png',
      'len3.png',
      'len30.png',
      'len31.png',
      'len4.png',
      'len5.png',
      'len6.png',
      'len7.png',
      'len8.png',
      'len9.png',
    ],
    'luka': [
      'luka1.png',
      'luka10.png',
      'luka11.png',
      'luka12.png',
      'luka13.png',
      'luka14.png',
      'luka15.png',
      'luka16.png',
      'luka17.png',
      'luka18.png',
      'luka19.png',
      'luka2.png',
      'luka20.png',
      'luka21.png',
      'luka22.png',
      'luka23.png',
      'luka24.png',
      'luka25.png',
      'luka3.png',
      'luka4.png',
      'luka5.png',
      'luka6.png',
      'luka7.png',
      'luka8.png',
      'luka9.png',
    ],
    'mafuyu': [
      'mafuyu1.png',
      'mafuyu10.png',
      'mafuyu11.png',
      'mafuyu12.png',
      'mafuyu13.png',
      'mafuyu14.png',
      'mafuyu15.png',
      'mafuyu16.png',
      'mafuyu17.png',
      'mafuyu18.png',
      'mafuyu19.png',
      'mafuyu2.png',
      'mafuyu20.png',
      'mafuyu21.png',
      'mafuyu22.png',
      'mafuyu23.png',
      'mafuyu24.png',
      'mafuyu25.png',
      'mafuyu26.png',
      'mafuyu27.png',
      'mafuyu28.png',
      'mafuyu3.png',
      'mafuyu4.png',
      'mafuyu5.png',
      'mafuyu6.png',
      'mafuyu7.png',
      'mafuyu8.png',
      'mafuyu9.png',
    ],
    'meiko': [
      'meiko1.png',
      'meiko10.png',
      'meiko11.png',
      'meiko12.png',
      'meiko13.png',
      'meiko14.png',
      'meiko15.png',
      'meiko16.png',
      'meiko17.png',
      'meiko18.png',
      'meiko19.png',
      'meiko2.png',
      'meiko20.png',
      'meiko21.png',
      'meiko22.png',
      'meiko23.png',
      'meiko24.png',
      'meiko25.png',
      'meiko26.png',
      'meiko27.png',
      'meiko28.png',
      'meiko29.png',
      'meiko3.png',
      'meiko30.png',
      'meiko31.png',
      'meiko32.png',
      'meiko33.png',
      'meiko4.png',
      'meiko5.png',
      'meiko6.png',
      'meiko7.png',
      'meiko8.png',
      'meiko9.png',
    ],
    'miku': [
      'miku1.png',
      'miku10.png',
      'miku11.png',
      'miku12.png',
      'miku13.png',
      'miku14.png',
      'miku15.png',
      'miku16.png',
      'miku17.png',
      'miku18.png',
      'miku19.png',
      'miku2.png',
      'miku20.png',
      'miku21.png',
      'miku22.png',
      'miku23.png',
      'miku24.png',
      'miku25.png',
      'miku26.png',
      'miku27.png',
      'miku28.png',
      'miku29.png',
      'miku3.png',
      'miku30.png',
      'miku31.png',
      'miku32.png',
      'miku33.png',
      'miku34.png',
      'miku35.png',
      'miku36.png',
      'miku37.png',
      'miku38.png',
      'miku39.png',
      'miku4.png',
      'miku40.png',
      'miku41.png',
      'miku5.png',
      'miku6.png',
      'miku7.png',
      'miku8.png',
      'miku9.png',
    ],
    'minori': [
      'minori1.png',
      'minori10.png',
      'minori11.png',
      'minori12.png',
      'minori13.png',
      'minori14.png',
      'minori15.png',
      'minori16.png',
      'minori17.png',
      'minori18.png',
      'minori19.png',
      'minori2.png',
      'minori20.png',
      'minori21.png',
      'minori22.png',
      'minori23.png',
      'minori24.png',
      'minori25.png',
      'minori26.png',
      'minori27.png',
      'minori28.png',
      'minori29.png',
      'minori3.png',
      'minori30.png',
      'minori31.png',
      'minori32.png',
      'minori4.png',
      'minori5.png',
      'minori6.png',
      'minori7.png',
      'minori8.png',
      'minori9.png',
    ],
    'mizuki': [
      'mizuki1.png',
      'mizuki10.png',
      'mizuki11.png',
      'mizuki12.png',
      'mizuki13.png',
      'mizuki14.png',
      'mizuki15.png',
      'mizuki16.png',
      'mizuki17.png',
      'mizuki18.png',
      'mizuki19.png',
      'mizuki2.png',
      'mizuki20.png',
      'mizuki21.png',
      'mizuki22.png',
      'mizuki23.png',
      'mizuki24.png',
      'mizuki25.png',
      'mizuki26.png',
      'mizuki27.png',
      'mizuki28.png',
      'mizuki29.png',
      'mizuki3.png',
      'mizuki4.png',
      'mizuki5.png',
      'mizuki6.png',
      'mizuki7.png',
      'mizuki8.png',
      'mizuki9.png',
    ],
    'nene': [
      'nene1.png',
      'nene10.png',
      'nene11.png',
      'nene12.png',
      'nene13.png',
      'nene14.png',
      'nene15.png',
      'nene16.png',
      'nene17.png',
      'nene18.png',
      'nene19.png',
      'nene2.png',
      'nene20.png',
      'nene21.png',
      'nene22.png',
      'nene23.png',
      'nene24.png',
      'nene25.png',
      'nene26.png',
      'nene27.png',
      'nene3.png',
      'nene4.png',
      'nene5.png',
      'nene6.png',
      'nene7.png',
      'nene8.png',
      'nene9.png',
    ],
    'rin': [
      'rin1.png',
      'rin10.png',
      'rin11.png',
      'rin12.png',
      'rin13.png',
      'rin14.png',
      'rin15.png',
      'rin16.png',
      'rin17.png',
      'rin18.png',
      'rin19.png',
      'rin2.png',
      'rin20.png',
      'rin21.png',
      'rin22.png',
      'rin23.png',
      'rin24.png',
      'rin25.png',
      'rin26.png',
      'rin27.png',
      'rin28.png',
      'rin29.png',
      'rin3.png',
      'rin30.png',
      'rin31.png',
      'rin32.png',
      'rin33.png',
      'rin4.png',
      'rin5.png',
      'rin6.png',
      'rin7.png',
      'rin8.png',
      'rin9.png',
    ],
    'rui': [
      'rui1.png',
      'rui10.png',
      'rui11.png',
      'rui12.png',
      'rui13.png',
      'rui14.png',
      'rui15.png',
      'rui16.png',
      'rui17.png',
      'rui18.png',
      'rui19.png',
      'rui2.png',
      'rui20.png',
      'rui21.png',
      'rui22.png',
      'rui23.png',
      'rui24.png',
      'rui25.png',
      'rui26.png',
      'rui27.png',
      'rui28.png',
      'rui29.png',
      'rui3.png',
      'rui4.png',
      'rui5.png',
      'rui6.png',
      'rui7.png',
      'rui8.png',
      'rui9.png',
    ],
    'saki': [
      'saki1.png',
      'saki10.png',
      'saki11.png',
      'saki12.png',
      'saki13.png',
      'saki14.png',
      'saki15.png',
      'saki16.png',
      'saki17.png',
      'saki18.png',
      'saki19.png',
      'saki2.png',
      'saki20.png',
      'saki21.png',
      'saki22.png',
      'saki23.png',
      'saki24.png',
      'saki25.png',
      'saki26.png',
      'saki27.png',
      'saki28.png',
      'saki29.png',
      'saki3.png',
      'saki30.png',
      'saki4.png',
      'saki5.png',
      'saki6.png',
      'saki7.png',
      'saki8.png',
      'saki9.png',
    ],
    'shiho': [
      'shiho1.png',
      'shiho10.png',
      'shiho11.png',
      'shiho12.png',
      'shiho13.png',
      'shiho14.png',
      'shiho15.png',
      'shiho16.png',
      'shiho17.png',
      'shiho18.png',
      'shiho19.png',
      'shiho2.png',
      'shiho20.png',
      'shiho21.png',
      'shiho22.png',
      'shiho23.png',
      'shiho24.png',
      'shiho25.png',
      'shiho26.png',
      'shiho27.png',
      'shiho28.png',
      'shiho29.png',
      'shiho3.png',
      'shiho30.png',
      'shiho31.png',
      'shiho4.png',
      'shiho5.png',
      'shiho6.png',
      'shiho7.png',
      'shiho8.png',
      'shiho9.png',
    ],
    'shizuku': [
      'shizuku1.png',
      'shizuku10.png',
      'shizuku11.png',
      'shizuku12.png',
      'shizuku13.png',
      'shizuku14.png',
      'shizuku15.png',
      'shizuku16.png',
      'shizuku17.png',
      'shizuku18.png',
      'shizuku19.png',
      'shizuku2.png',
      'shizuku20.png',
      'shizuku21.png',
      'shizuku22.png',
      'shizuku23.png',
      'shizuku24.png',
      'shizuku25.png',
      'shizuku26.png',
      'shizuku27.png',
      'shizuku28.png',
      'shizuku3.png',
      'shizuku4.png',
      'shizuku5.png',
      'shizuku6.png',
      'shizuku7.png',
      'shizuku8.png',
      'shizuku9.png',
    ],
    'touya': [
      'touya1.png',
      'touya10.png',
      'touya11.png',
      'touya12.png',
      'touya13.png',
      'touya14.png',
      'touya15.png',
      'touya16.png',
      'touya17.png',
      'touya18.png',
      'touya19.png',
      'touya2.png',
      'touya20.png',
      'touya21.png',
      'touya22.png',
      'touya23.png',
      'touya24.png',
      'touya25.png',
      'touya26.png',
      'touya27.png',
      'touya28.png',
      'touya29.png',
      'touya3.png',
      'touya30.png',
      'touya31.png',
      'touya4.png',
      'touya5.png',
      'touya6.png',
      'touya7.png',
      'touya8.png',
      'touya9.png',
    ],
    'tsukasa': [
      'tsukasa1.png',
      'tsukasa10.png',
      'tsukasa11.png',
      'tsukasa12.png',
      'tsukasa13.png',
      'tsukasa14.png',
      'tsukasa15.png',
      'tsukasa16.png',
      'tsukasa17.png',
      'tsukasa18.png',
      'tsukasa19.png',
      'tsukasa2.png',
      'tsukasa20.png',
      'tsukasa21.png',
      'tsukasa22.png',
      'tsukasa23.png',
      'tsukasa24.png',
      'tsukasa25.png',
      'tsukasa26.png',
      'tsukasa27.png',
      'tsukasa28.png',
      'tsukasa29.png',
      'tsukasa3.png',
      'tsukasa30.png',
      'tsukasa4.png',
      'tsukasa5.png',
      'tsukasa6.png',
      'tsukasa7.png',
      'tsukasa8.png',
      'tsukasa9.png',
    ],
    'haruka': [
      'haruka1.png',
      'haruka10.png',
      'haruka11.png',
      'haruka12.png',
      'haruka13.png',
      'haruka14.png',
      'haruka15.png',
      'haruka16.png',
      'haruka17.png',
      'haruka18.png',
      'haruka19.png',
      'haruka2.png',
      'haruka20.png',
      'haruka21.png',
      'haruka22.png',
      'haruka23.png',
      'haruka24.png',
      'haruka25.png',
      'haruka26.png',
      'haruka27.png',
      'haruka28.png',
      'haruka29.png',
      'haruka3.png',
      'haruka4.png',
      'haruka5.png',
      'haruka6.png',
      'haruka7.png',
      'haruka8.png',
      'haruka9.png',
    ],
  };

  static final Map<String, Color> characterColor = {
    "airi": Color.fromARGB(255, 216, 95, 116),
    "akito": Color.fromARGB(255, 224, 94, 62),
    "an": Color.fromARGB(255, 91, 91, 106),
    "emu": Color.fromARGB(255, 212, 129, 169),
    "ena": Color.fromARGB(255, 109, 91, 101),
    "haruka": Color.fromARGB(255, 49, 94, 168),
    "honami": Color.fromARGB(255, 172, 125, 130),
    "ichika": Color.fromARGB(255, 77, 93, 127),
    "kaito": Color.fromARGB(255, 46, 63, 181),
    "kanade": Color.fromARGB(255, 176, 185, 214),
    "kohane": Color.fromARGB(255, 182, 172, 145),
    "len": Color.fromARGB(255, 244, 224, 135),
    "luka": Color.fromARGB(255, 240, 198, 223),
    "mafuyu": Color.fromARGB(255, 97, 72, 146),
    "meiko": Color.fromARGB(255, 168, 136, 93),
    "miku": Color.fromARGB(255, 128, 194, 197),
    "minori": Color.fromARGB(255, 201, 142, 124),
    "mizuki": Color.fromARGB(255, 217, 179, 176),
    "nene": Color.fromARGB(255, 183, 186, 174),
    "rin": Color.fromARGB(255, 246, 231, 141),
    "rui": Color.fromARGB(255, 206, 160, 240),
    "saki": Color.fromARGB(255, 246, 201, 217),
    "shiho": Color.fromARGB(255, 179, 173, 179),
    "shizuku": Color.fromARGB(255, 141, 170, 197),
    "touya": Color.fromARGB(255, 167, 180, 222),
    "tsukasa": Color.fromARGB(255, 235, 190, 155),
  };

  static final Map<String, int> characterLen = {
    'airi': 30,
    'akito': 28,
    'an': 30,
    'emu': 27,
    'ena': 29,
    'haruka': 29,
    'honami': 30,
    'ichika': 33,
    'kaito': 31,
    'kanade': 33,
    'kohane': 29,
    'len': 31,
    'luka': 25,
    'mafuyu': 28,
    'meiko': 33,
    'miku': 41,
    'minori': 32,
    'mizuki': 29,
    'nene': 27,
    'rin': 33,
    'rui': 29,
    'saki': 30,
    'shiho': 31,
    'shizuku': 28,
    'touya': 31,
    'tsukasa': 30,
  };

  static final characterList = [
    "airi",
    "akito",
    "an",
    "emu",
    "ena",
    "haruka",
    "honami",
    "ichika",
    "kaito",
    "kanade",
    "kohane",
    "len",
    "luka",
    "mafuyu",
    "meiko",
    "miku",
    "minori",
    "mizuki",
    "nene",
    "rin",
    "rui",
    "saki",
    "shiho",
    "shizuku",
    "touya",
    "tsukasa",
  ];

  static final List<String> fonts = ["YurukaStd", "ShangShouFangTangTi"];

  /// 清理所有静态缓存（图片和字体）
  static void clearCache() {
    _imageCache.clear();
    _fontCache.clear();
  }

  static Future<Uint8List> pjsk({
    required List<TextLayer> layers,
    String character = "",
  }) async {
    // 1. 确定角色名称
    String characterName = character.toLowerCase().replaceAll(
      RegExp(r"[^a-z]"),
      "",
    );
    
    // 如果角色不在列表中，随机选一个或默认用 miku
    if (!characterList.contains(characterName)) {
      characterName = "miku";
    }

    // 2. 确定角色贴纸编号
    int charNum = int.tryParse(character.replaceAll(RegExp(r"[^0-9]"), "")) ?? 1;
    final int maxNum = characterLen[characterName] ?? 1;
    if (charNum < 1 || charNum > maxNum) {
      charNum = 1;
    }

    // 3. 确定背景图片路径并从缓存加载
    final String charPath = "assets/characters/$characterName/$characterName$charNum.png";
    
    if (!_imageCache.containsKey(charPath)) {
      // 内存管理：缓存超过 30 张图片时移除最旧的一张 (FIFO)
      if (_imageCache.length >= 30) {
        _imageCache.remove(_imageCache.keys.first);
      }
      
      try {
        final bgImageData = await rootBundle.load(charPath);
        _imageCache[charPath] = bgImageData.buffer.asUint8List();
      } catch (e) {
        if (kDebugMode) print("Error loading image $charPath: $e");
        // 如果特定编号失败，回退到 1.png
        try {
          final fallbackPath = "assets/characters/$characterName/${characterName}1.png";
          final bgImageData = await rootBundle.load(fallbackPath);
          _imageCache[charPath] = bgImageData.buffer.asUint8List();
        } catch (e2) {
          // 极致回退
          final bgImageData = await rootBundle.load("assets/characters/miku/miku1.png");
          _imageCache[charPath] = bgImageData.buffer.asUint8List();
        }
      }
    }
    final Uint8List bgImageBytes = _imageCache[charPath]!;

    // 4. 预加载所有需要的字体（带缓存）
    for (var layer in layers) {
      if (!_fontCache.containsKey(layer.font)) {
        final int fontIndex = layer.font.clamp(0, fonts.length - 1);
        final String fontFamilyName = fonts[fontIndex];
        final String fontAssetPath = "Fonts/$fontFamilyName.ttf";
        try {
          final ByteData fontData = await rootBundle.load(fontAssetPath);
          final bytes = fontData.buffer.asUint8List();
          if (bytes.isNotEmpty) {
            _fontCache[layer.font] = bytes;
          }
        } catch (e) {
          if (kDebugMode) print("Error loading font $fontAssetPath: $e");
          // 如果备用字体也失败，将不再尝试加载该索引
          if (layer.font != 0) {
             try {
               final fallbackData = await rootBundle.load("Fonts/${fonts[0]}.ttf");
               _fontCache[layer.font] = fallbackData.buffer.asUint8List();
             } catch (_) {}
          }
        }
      }
    }

    // 5. 准备渲染层
    List<TextOverlayLayer> renderLayers =
        layers.map((l) {
          final int fontIndex = l.font.clamp(0, fonts.length - 1);
          return TextOverlayLayer(
            content: l.content,
            fontFamilyName: fonts[fontIndex],
            fontBytes: _fontCache[l.font] ?? Uint8List(0),
            pos: l.pos,
            lean: l.lean,
            fontSize: l.fontSize,
            edgeSize: l.edgeSize,
            color: l.useCustomColor 
                ? l.customColor 
                : (characterColor[characterName] ?? Colors.pink),
          );
        }).toList();

    // 6. 调用核心函数进行图片合成
    return ImageTextOverlay.generateStickerFromBytes(
      imageBytes: bgImageBytes,
      layers: renderLayers,
    );
  }
}
